<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Clipensk.Infrastructure</RootNamespace>
    <AssemblyName>Clipensk.Infrastructure</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Konscious.Security.Cryptography.Argon2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Clipensk.Core\Clipensk.Core.csproj" />
  </ItemGroup>
</Project>
