using Clipensk.Core.Localization;

namespace Clipensk.Infrastructure.Localization;

public sealed class BuiltInRussianLocalizationService : ILocalizationService
{
    private static readonly IReadOnlyDictionary<string, string> Strings = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["App.Title"] = "Clipensk",
        ["Journal.Title"] = "Журнал",
        ["Journal.Empty"] = "История буфера обмена пока не загружена.",
        ["Navigation.Journal"] = "Журнал",
        ["Navigation.Applications"] = "Приложения",
        ["Navigation.Maintenance"] = "Обслуживание",
        ["Navigation.Settings"] = "Настройки",
        ["Navigation.About"] = "О программе",
        ["Page.Applications.Title"] = "Приложения и правила сбора",
        ["Page.Maintenance.Title"] = "Обслуживание баз данных",
        ["Page.Settings.Title"] = "Настройки Clipensk",
        ["Page.About.Title"] = "О программе Clipensk",
        ["FirstRun.Title"] = "Первоначальная настройка",
        ["FirstRun.Body"] = "До создания баз данных и запуска журналирования выберите каталог, в котором Clipensk будет хранить пользовательские данные. Каталог будет проверен на доступность записи до сохранения настройки.",
        ["FirstRun.ChooseDataRoot"] = "Выбрать каталог данных",
        ["FirstRun.ValidationFailed"] = "Не удалось использовать выбранный каталог. Проверьте доступность записи и отсутствие повреждённых метаданных Clipensk, затем выберите другой каталог.",
        ["FirstRun.SavedLocked"] = "Каталог данных сохранён. Clipensk остаётся заблокированным до успешной настройки или проверки пароля.",
        ["Lock.Title"] = "Clipensk заблокирован",
        ["Lock.Body"] = "История и сбор данных буфера обмена недоступны до разблокировки. Без чтения защищённых данных доступны безопасные настройки и обслуживание.",
        ["Lock.SetupTitle"] = "Создание пароля Clipensk",
        ["Lock.SetupBody"] = "Для этого каталога ещё не настроен MasterKey. Задайте пароль и подтвердите его. Пароль не будет сохранён; из него будет выводиться MasterKey с помощью Argon2id.",
        ["Lock.PasswordHint"] = "Подсказка к паролю",
        ["Lock.PasswordHintEmpty"] = "Подсказка не задана.",
        ["Lock.SetupHint"] = "Подсказка к паролю (необязательно)",
        ["Lock.SetupHintPlaceholder"] = "Комментарий, который можно показать до разблокировки",
        ["Lock.PasswordPlaceholder"] = "Введите пароль",
        ["Lock.ConfirmPassword"] = "Подтверждение пароля",
        ["Lock.ConfirmPasswordPlaceholder"] = "Введите пароль ещё раз",
        ["Lock.Unlock"] = "Разблокировать",
        ["Lock.InitializeAndUnlock"] = "Создать защиту и разблокировать",
        ["Lock.PasswordRequired"] = "Введите пароль.",
        ["Lock.PasswordMismatch"] = "Пароль и подтверждение не совпадают.",
        ["Lock.InvalidPassword"] = "Пароль неверен. Clipensk остаётся заблокированным.",
        ["Lock.InvalidMetadata"] = "Криптографические метаданные каталога повреждены, недоступны или имеют неподдерживаемый формат. Clipensk остаётся заблокированным.",
        ["Lock.EncryptionEngineUnavailable"] = "Native SQLCipher недоступен или не прошёл проверку шифрования. Clipensk остаётся заблокированным.",
        ["Lock.StorageMissingOrPartial"] = "Набор защищённых БД неполон или противоречит существующим данным. Автоматическое создание поверх такого состояния запрещено.",
        ["Lock.StorageIdentityInvalid"] = "Защищённая БД не прошла проверку ключа, целостности или DatabaseIdentity. Clipensk остаётся заблокированным.",
        ["Lock.StorageOpenFailed"] = "Не удалось открыть или инициализировать защищённое хранилище. Clipensk остаётся заблокированным.",
        ["Lock.UnlockFailed"] = "Не удалось выполнить защищённую разблокировку. Clipensk остаётся заблокированным.",
        ["CapturePolicy.Title"] = "Правила сбора",
        ["CapturePolicy.Body"] = "Правила относятся к выбранному хранилищу. Базовое правило и правила стандартных форматов можно изменять после первоначальной настройки; индивидуальные правила приложений могут переопределять базовое правило.",
        ["CapturePolicy.BaseRule"] = "Базовое правило сбора",
        ["CapturePolicy.ChooseRule"] = "Выберите действие",
        ["CapturePolicy.Allow"] = "Разрешить",
        ["CapturePolicy.Deny"] = "Запретить",
        ["CapturePolicy.Formats"] = "Стандартные форматы",
        ["CapturePolicy.CustomFormats"] = "Пользовательские бинарные форматы",
        ["CapturePolicy.CustomFormatsHelp"] = "Добавляйте только точные имена зарегистрированных/private форматов Windows, которые должны обрабатываться как бинарный поток. Для разрешённого формата задайте расширение внешнего файла; оно будет сохранено вместе с первоначальной policy в одной транзакции.",
        ["CapturePolicy.AddCustomFormat"] = "Добавить пользовательский формат",
        ["CapturePolicy.RemoveCustomFormat"] = "Удалить формат из первоначальной настройки",
        ["CapturePolicy.CustomFormatName"] = "Точное имя формата",
        ["CapturePolicy.CustomFormatNamePlaceholder"] = "Например Vendor.Product.Binary",
        ["CapturePolicy.CustomRule"] = "Правило пользовательского формата",
        ["CapturePolicy.CustomFileExtension"] = "Расширение внешнего файла",
        ["CapturePolicy.CustomFileExtensionPlaceholder"] = "Например .binx",
        ["CapturePolicy.CustomExtensionMissing"] = "не настроено — новый payload будет отклонён",
        ["CapturePolicy.LimitMode"] = "Ограничение размера",
        ["CapturePolicy.ChooseLimit"] = "Выберите ограничение",
        ["CapturePolicy.Limited"] = "Задать лимит в байтах",
        ["CapturePolicy.Unlimited"] = "Без лимита",
        ["CapturePolicy.Bytes"] = "Максимальный размер, байт",
        ["CapturePolicy.ByteUnit"] = "байт",
        ["CapturePolicy.BytesPlaceholder"] = "Положительное целое число",
        ["CapturePolicy.LimitsHelp"] = "Для разрешённых форматов выберите лимит или явно укажите «Без лимита». Текст и ссылки измеряются в байтах UTF-8, изображения — после преобразования в PNG, список файлов — по размеру текстовых сведений. Содержимое выбранных файлов не копируется.",
        ["CapturePolicy.ExternalHelp"] = "Изображения и пользовательские бинарные payload сохраняются отдельными файлами и не защищаются паролем базы данных. Для нового custom-binary SHA требуется заранее сохранённое точное соответствие FormatName → расширение файла.",
        ["CapturePolicy.SetupHelp"] = "Первоначальное сохранение создаёт policy и custom-binary mappings атомарно. После настройки можно безопасно менять базовое правило и стандартные форматы; существующие custom-binary правила и mappings при таком изменении сохраняются без изменений.",
        ["CapturePolicy.Save"] = "Сохранить первоначальные правила",
        ["CapturePolicy.Edit"] = "Изменить правила",
        ["CapturePolicy.Reload"] = "Перечитать правила и сбросить ввод",
        ["CapturePolicy.Open"] = "Открыть правила сбора",
        ["CapturePolicy.ValidationFailed"] = "Выберите базовое правило и действие для каждого формата. Для разрешённых форматов выберите «Без лимита» либо задайте положительное целое число байт. Для разрешённого пользовательского бинарного формата укажите допустимое расширение файла и не используйте запрещённые WaveAudio, RiffAudio или FileContents.",
        ["CapturePolicy.SaveFailed"] = "Не удалось подтвердить атомарное сохранение. Перечитайте правила перед повторной настройкой: durable configuration могла быть создана другим действием.",
        ["CapturePolicy.State.Locked"] = "Правила сбора доступны после разблокировки хранилища.",
        ["CapturePolicy.State.Loading"] = "Загрузка правил сбора…",
        ["CapturePolicy.State.Unconfigured"] = "Первоначальные правила ещё не заданы. Сбор истории не выполняется.",
        ["CapturePolicy.State.Saving"] = "Сохранение первоначальных правил и пользовательских mappings…",
        ["CapturePolicy.State.Configured"] = "Правила сохранены. Пока хранилище разблокировано, resident capture runtime использует эту policy. Базовое правило и стандартные форматы можно изменить безопасным обслуживанием; custom-binary mappings при этом не меняются.",
        ["CapturePolicy.State.Failed"] = "Не удалось загрузить правила. Проверьте доступность хранилища и повторите чтение.",
        ["CapturePolicy.Format.Text"] = "Обычный текст",
        ["CapturePolicy.Format.Html"] = "HTML",
        ["CapturePolicy.Format.Rtf"] = "Форматированный текст RTF",
        ["CapturePolicy.Format.Bitmap"] = "Изображения",
        ["CapturePolicy.Format.WebLink"] = "Веб-ссылки",
        ["CapturePolicy.Format.ApplicationLink"] = "Ссылки приложений",
        ["CapturePolicy.Format.StorageItems"] = "Список файлов и папок",
        ["ApplicationPolicy.Title"] = "Приложения",
        ["ApplicationPolicy.Body"] = "Выберите обнаруженное приложение, чтобы посмотреть его индивидуальную политику сбора. Базовое правило, стандартные форматы и их лимиты можно изменить безопасным обслуживанием; пользовательские/private форматные переопределения сохраняются без изменений.",
        ["ApplicationPolicy.Edit"] = "Изменить индивидуальную политику",
        ["ApplicationPolicy.Reload"] = "Перечитать приложения",
        ["ApplicationPolicy.Empty"] = "Обнаруженных приложений пока нет. Они появятся после успешного определения источника захвата.",
        ["ApplicationPolicy.LoadFailed"] = "Не удалось загрузить список приложений из защищённого хранилища.",
        ["ApplicationPolicy.ReadFailed"] = "Не удалось прочитать индивидуальное правило выбранного приложения.",
        ["ApplicationPolicy.BaseRule"] = "Базовое правило приложения",
        ["ApplicationPolicy.Inherit"] = "Наследовать глобальное правило",
        ["ApplicationPolicy.Formats"] = "Стандартные форматы приложения",
        ["ApplicationPolicy.FormatsHelp"] = "Для каждого стандартного формата можно наследовать, разрешить или запретить правило. Лимит размера наследуется из глобальной политики, пока вы явно не зададите положительный лимит в байтах для этого приложения.",
        ["ApplicationPolicy.InheritLimit"] = "Наследовать глобальный лимит",
        ["ApplicationPolicy.OverrideLimit"] = "Переопределить лимит в байтах",
        ["ApplicationPolicy.EditHelp"] = "Изменяются базовое правило и стандартные форматы приложения. Существующие пользовательские/private форматные переопределения сохраняются без изменений.",
        ["ApplicationPolicy.ValidationFailed"] = "Проверьте правило каждого стандартного формата. Для переопределённого лимита укажите положительное целое число байт; режим наследования использует глобальный лимит.",
        ["ApplicationPolicy.Apply"] = "Применить",
        ["ApplicationPolicy.Cancel"] = "Отмена",
        ["ApplicationPolicy.SessionChanged"] = "Защищённая сессия изменилась. Закройте диалог и повторите после разблокировки.",
        ["ApplicationPolicy.ApplyFailed"] = "Изменение не завершено. Если durable-операция уже началась, сбор оставлен безопасно приостановленным и будет продолжен при следующей разблокировке.",
        ["ApplicationPolicy.Saved"] = "Индивидуальная политика приложения сохранена.",
        ["ApplicationPolicy.PrepareFailed"] = "Не удалось подготовить или применить индивидуальную политику приложения.",
        ["ApplicationPolicy.Paths"] = "Пути",
        ["ApplicationPolicy.NoOverride"] = "Индивидуальное правило не задано; используется глобальная политика.",
        ["ApplicationPolicy.Summary"] = "Базовое правило: {0}. Форматных переопределений: {1}.",
        ["Settings.DataRoot.Title"] = "Каталог данных",
        ["Settings.DataRoot.NotConfigured"] = "Не настроен",
        ["Settings.HotKey.Title"] = "Горячая клавиша вызова журнала",
        ["Settings.HotKey.Key"] = "Основная клавиша",
        ["Settings.HotKey.Apply"] = "Применить горячую клавишу",
        ["Settings.HotKey.Saved"] = "Горячая клавиша сохранена и активирована.",
        ["Settings.HotKey.Failed"] = "Не удалось применить горячую клавишу. Прежняя комбинация сохранена.",
    };

    public string GetString(string key)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(key);
        return Strings.TryGetValue(key, out string? value) ? value : key;
    }
}
